# Nome do nosso workflow de automação
name: Build do Projeto Java EE

# Define quando este workflow deve ser executado
on:
  # Executa sempre que houver um push para o branch 'main'
  push:
    branches: [ "main" ]
  # Também permite que você o execute manualmente a partir da interface do GitHub
  workflow_dispatch:

# Define os "trabalhos" (jobs) que o nosso robô irá executar
jobs:
  build:
    # O robô irá correr numa máquina virtual com a última versão do Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Passo 1: O robô "clona" o seu repositório para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # Passo 2: O robô instala e configura o Java 17
      - name: Configurar o JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Passo 3: O robô executa o comando de build do Maven
      # Se este comando falhar, o workflow inteiro falha
      - name: Compilar com o Maven
        run: mvn -B clean install

